---
version: 3

vars:
  PROJECT_DIR:
    sh: 'git rev-parse --show-toplevel'

includes:
  pc:
    taskfile: .taskfiles/pre-commit

tasks:
  create-release:
    desc: Create a release
    silent: true
    cmds:
      - task: check
      - scripts/release {{.release}}
    vars:
      release: '{{ or .release (fail "Argument (release) is required") }}'

  release:
    desc: Push and build the release
    silent: true
    cmds:
      - git push
      - git push --tags

  staging:
    desc: Relaunch staging deployment
    silent: true
    cmds:
      - kubectl --context admin@staging rollout restart deployment -n self-hosted wordacle
      - kubectl --context admin@staging rollout status deployment -n self-hosted wordacle

  check:
    desc: Check code formatting / lint
    cmds:
      - npm run format
      - npm run lint

  fix:
    desc: Fix lint warnings
    cmds:
      - npm run lint -- --fix

  dev:
    desc: Run development server
    cmds:
      - npm run dev -- --open
