extends: default

ignore: |
  *.sops.*
  .vscode/
  build/
  node_modules/
  test-results/

rules:
  line-length:
    max: 120
  document-start: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
